server:
  port: 8080

logging.level:
  org.hibernate.SQL: debug

spring:
  config:
    import:
      - classpath:/yaml/application-local.yml
      - classpath:/yaml/application-prod.yml
      - classpath:/yaml/application-aws.yml
      - classpath:/yaml/application-secret.yml

  profiles:
    active: local #default
    group:
      local:
        - local
        - aws
        - secret
      prod:
        - prod
        - aws
        - -secret
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: prod