server:
  port: 8080

# log setting
logging:
  level:
    com:
      USWRandomChat:
        backend: debug

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/Plog
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true