spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: secret

  mail:
    host: smtp.gmail.com
    port: 587
    username: nkdy50315031@gmail.com
    password: zczxsylqqelzckrq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
