# log setting
logging:
  level:
    com:
      Plog:
        backend: debug

#email url
email:
  config:
    baseUrl: "http://localhost:8080"

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/Plog
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
